const IMAGE_SRC: Record<string, string> = {
	betia_login_logo: '/images/betia_login_logo.svg',
	betia_main_logo_1: '/images/betia_main_logo_1.svg',
	betia_main_logo_2: '/images/betia_main_logo_2.svg',
	checked_disabled: '/images/checked_disabled.svg',
	checked: '/images/checked.svg',
	clipboard_outline_active: '/images/clipboard_outline_active.svg',
	clipboard_outline: '/images/clipboard_outline.svg',
	error_image: '/images/error_image.svg',
	inbox_stack_outline: '/images/inbox_stack_outline.svg',
	need_to_search: '/images/need_to_search.svg',
	non_actived_learner: '/images/non_actived_learner.svg',
	non_actived_message: '/images/non_actived_message.svg',
	non_actived_notice: '/images/non_actived_notice.svg',
	non_exist_message: '/images/non_exist_message.svg',
	non_founded_data: '/images/non_founded_data.svg',
	notice_popup: '/images/notice_popup.svg',
	radio_disabled: '/images/radio_disabled.svg',
	radio: '/images/radio.svg',
	toast_question: '/images/toast_question.svg',
	toast_success: '/images/toast_success.svg',
	toast_warning: '/images/toast_warning.svg',
	user_circle_outline_active: '/images/user_circle_outline_active.svg',
	user_circle_outline: '/images/user_circle_outline.svg',
	vector_dark: '/images/vector_dark.svg',
	vector_white: '/images/vector_white.svg',
};

export { IMAGE_SRC };
